package com.fiserv.jarvis.forms;

import com.fiserv.jarvis.utils.ParserUtil;
import com.fiserv.jarvis.utils.Utils;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class frmParser extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmParser
     */
    public frmParser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cboxStruct = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnParser = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblParser = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMessageArea = new javax.swing.JTextArea();
        chkEspacios = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Message Paser");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.add(cboxStruct, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 110, -1));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setText("Input Type Struct:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, -1));

        btnParser.setText("Parser >>");
        btnParser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParserActionPerformed(evt);
            }
        });
        jPanel1.add(btnParser, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 200, 40));

        jScrollPane5.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 153), 2, true), "Detail:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 51, 153))); // NOI18N
        jScrollPane5.setForeground(new java.awt.Color(0, 51, 153));

        tblParser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Field", "Content"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblParser);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 480, 590));

        txtMessageArea.setColumns(20);
        txtMessageArea.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txtMessageArea.setRows(5);
        txtMessageArea.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 3, true), "Insert Record or Message", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 153, 255))); // NOI18N
        jScrollPane3.setViewportView(txtMessageArea);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 600, 540));

        chkEspacios.setText("Con Espacios a Izq.");
        jPanel1.add(chkEspacios, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 130, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 1110, 609));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnParserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParserActionPerformed
        boolean tieneEspacios = false; 
        String dll = Utils.getProperty( propertyFile , "directory.root.Libs.ddls"); 
        String tkn = Utils.getProperty( propertyFile , "directory.root.Libs.tkns");
        List<String> registrosTabla;

        //Busco el archivo y convierto en lista los datos para usar en el parser
        List<String> lista = ParserUtil.getContentField(dll, tkn, cboxStruct.getSelectedItem().toString());

        //lista de objetos con estructura [ posicion, largo, nombre ]
        List<String> listMapper = ParserUtil.FileMapper(lista);

        //Lo mando a procesar y obtengo una lista <clave, valor> y completo el JTable
        if(chkEspacios.isSelected()){
            tieneEspacios = true;
        }

        registrosTabla = ParserUtil.ParserExecute(listMapper, txtMessageArea.getText(), tieneEspacios);

        //Relleno la Tabla
        DefaultTableModel tblModel =new DefaultTableModel();
        tblModel = (DefaultTableModel) tblParser.getModel();

        String[] campos =new String[2];
        for(String s : registrosTabla){
            campos = s.split(",");
            tblModel.addRow(campos);
        }
        tblParser.setModel(tblModel);
       
    }//GEN-LAST:event_btnParserActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        
        String listaStructs = Utils.getProperty( propertyFile , "library.struct");
        
        String[] listArray = listaStructs.split(",");
        
        for(String s : listArray){
            cboxStruct.addItem(s);
        }
        
    }//GEN-LAST:event_formInternalFrameOpened


    private static String propertyFile = "C:\\Jarvis\\Config\\Properties";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnParser;
    private javax.swing.JComboBox<String> cboxStruct;
    private javax.swing.JCheckBox chkEspacios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblParser;
    private javax.swing.JTextArea txtMessageArea;
    // End of variables declaration//GEN-END:variables
}
